HTTP_PORT: 3002
DATABASE_URL: postgres://postgres:postgres@localhost:5432/go_crawler?sslmode=disable
DATABASE_TESTURL: postgres://postgres:postgres@localhost:5432/go_crawler_test?sslmode=disable
REDIS_URL: redis://localhost:6379/7
WORKERS: CollectIpWorker,QcloudSmsWorker

